import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Import your global styles here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sora font-source-code-pro font-space-grotesk`}>{children}</body>
    </html>
  );
}
